name : essence_report

on:
  schedule:
    - cron : '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.x
      - name: install packages
        run:
          pip install -r requirements.txt
      - name: run essence
        env:
          user_email: ${{ secrets.user_email }}
          email_token: ${{ secrets.email_token }}
          recipients: ${{ secrets.recipients }}
        run: python essence_cost_live.py
